os: osx # enable this if you need macOS support
language: ruby
rvm:
  - 2.4.1

install:
  - brew install blender/homebrew-tap/rome
  - gem install bundler

script:
  # Run bundler and install the dependencies in vendor/bundle
  # so that it can be cached.
  - bundle install
  - rake
